/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ModalOptions } from "./components/wallet-selector/modal.types";
import { Theme } from "./components/wallet-selector-modal/wallet-selector-modal";
import { Components } from "./components";
export namespace Components {
    interface AlertMessage {
        "message": string;
    }
    interface CloseButton {
    }
    interface LedgerDerivationPath {
        "selector": any;
    }
    interface WalletNetworkChanged {
        "selector": any;
    }
    interface WalletOptions {
        "options"?: ModalOptions;
        "selector": any;
    }
    interface WalletSelector {
        "setRouteName": (route: string) => Promise<void>;
        "setSelector": (selector: unknown) => Promise<void>;
    }
    interface WalletSelectorModal {
        /**
          * Method to hide the modal
         */
        "hide": () => Promise<void>;
        "setSelector": (selector: unknown) => Promise<void>;
        /**
          * Method to show the modal.
         */
        "show": () => Promise<void>;
        /**
          * The prefered theme for the modal.
         */
        "theme": Theme;
    }
}
declare global {
    interface HTMLAlertMessageElement extends Components.AlertMessage, HTMLStencilElement {
    }
    var HTMLAlertMessageElement: {
        prototype: HTMLAlertMessageElement;
        new (): HTMLAlertMessageElement;
    };
    interface HTMLCloseButtonElement extends Components.CloseButton, HTMLStencilElement {
    }
    var HTMLCloseButtonElement: {
        prototype: HTMLCloseButtonElement;
        new (): HTMLCloseButtonElement;
    };
    interface HTMLLedgerDerivationPathElement extends Components.LedgerDerivationPath, HTMLStencilElement {
    }
    var HTMLLedgerDerivationPathElement: {
        prototype: HTMLLedgerDerivationPathElement;
        new (): HTMLLedgerDerivationPathElement;
    };
    interface HTMLWalletNetworkChangedElement extends Components.WalletNetworkChanged, HTMLStencilElement {
    }
    var HTMLWalletNetworkChangedElement: {
        prototype: HTMLWalletNetworkChangedElement;
        new (): HTMLWalletNetworkChangedElement;
    };
    interface HTMLWalletOptionsElement extends Components.WalletOptions, HTMLStencilElement {
    }
    var HTMLWalletOptionsElement: {
        prototype: HTMLWalletOptionsElement;
        new (): HTMLWalletOptionsElement;
    };
    interface HTMLWalletSelectorElement extends Components.WalletSelector, HTMLStencilElement {
    }
    var HTMLWalletSelectorElement: {
        prototype: HTMLWalletSelectorElement;
        new (): HTMLWalletSelectorElement;
    };
    interface HTMLWalletSelectorModalElement extends Components.WalletSelectorModal, HTMLStencilElement {
    }
    var HTMLWalletSelectorModalElement: {
        prototype: HTMLWalletSelectorModalElement;
        new (): HTMLWalletSelectorModalElement;
    };
    interface HTMLElementTagNameMap {
        "alert-message": HTMLAlertMessageElement;
        "close-button": HTMLCloseButtonElement;
        "ledger-derivation-path": HTMLLedgerDerivationPathElement;
        "wallet-network-changed": HTMLWalletNetworkChangedElement;
        "wallet-options": HTMLWalletOptionsElement;
        "wallet-selector": HTMLWalletSelectorElement;
        "wallet-selector-modal": HTMLWalletSelectorModalElement;
    }
}
declare namespace LocalJSX {
    interface AlertMessage {
        "message": string;
        "onNearBackEvent"?: (event: CustomEvent<MouseEvent>) => void;
    }
    interface CloseButton {
        "onNearModalCloseEvent"?: (event: CustomEvent<MouseEvent>) => void;
    }
    interface LedgerDerivationPath {
        "onNearBackEventLedger"?: (event: CustomEvent<MouseEvent>) => void;
        "onNearConnected"?: (event: CustomEvent<MouseEvent>) => void;
        "selector"?: any;
    }
    interface WalletNetworkChanged {
        "onNearSwitchWallet"?: (event: CustomEvent<string>) => void;
        "onNearWalletNetworkDismiss"?: (event: CustomEvent<string>) => void;
        "selector"?: any;
    }
    interface WalletOptions {
        "onNearConnectHardwareWallet"?: (event: CustomEvent<MouseEvent>) => void;
        "onNearConnected"?: (event: CustomEvent<void>) => void;
        "onNearErrorWalletOptions"?: (event: CustomEvent<string>) => void;
        "options"?: ModalOptions;
        "selector"?: any;
    }
    interface WalletSelector {
    }
    interface WalletSelectorModal {
        /**
          * The prefered theme for the modal.
         */
        "theme"?: Theme;
    }
    interface IntrinsicElements {
        "alert-message": AlertMessage;
        "close-button": CloseButton;
        "ledger-derivation-path": LedgerDerivationPath;
        "wallet-network-changed": WalletNetworkChanged;
        "wallet-options": WalletOptions;
        "wallet-selector": WalletSelector;
        "wallet-selector-modal": WalletSelectorModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alert-message": LocalJSX.AlertMessage & JSXBase.HTMLAttributes<HTMLAlertMessageElement>;
            "close-button": LocalJSX.CloseButton & JSXBase.HTMLAttributes<HTMLCloseButtonElement>;
            "ledger-derivation-path": LocalJSX.LedgerDerivationPath & JSXBase.HTMLAttributes<HTMLLedgerDerivationPathElement>;
            "wallet-network-changed": LocalJSX.WalletNetworkChanged & JSXBase.HTMLAttributes<HTMLWalletNetworkChangedElement>;
            "wallet-options": LocalJSX.WalletOptions & JSXBase.HTMLAttributes<HTMLWalletOptionsElement>;
            "wallet-selector": LocalJSX.WalletSelector & JSXBase.HTMLAttributes<HTMLWalletSelectorElement>;
            "wallet-selector-modal": LocalJSX.WalletSelectorModal & JSXBase.HTMLAttributes<HTMLWalletSelectorModalElement>;
        }
    }
}
