/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WalletSelector } from "@near-wallet-selector/core";
import { Theme } from "./modal.types";
import { Components } from "./components";
export namespace Components {
    interface CloseButton {
    }
    interface WalletSelector {
        "setRouteName": (route: string) => Promise<void>;
        "setSelector": (selector: WalletSelector) => Promise<void>;
    }
    interface WalletSelectorModal {
        /**
          * Method to hide the modal
         */
        "hide": () => Promise<void>;
        "setSelector": (selector: WalletSelector) => Promise<void>;
        /**
          * Method to show the modal.
         */
        "show": () => Promise<void>;
        /**
          * The prefered theme for the modal.
         */
        "theme": Theme;
    }
}
declare global {
    interface HTMLCloseButtonElement extends Components.CloseButton, HTMLStencilElement {
    }
    var HTMLCloseButtonElement: {
        prototype: HTMLCloseButtonElement;
        new (): HTMLCloseButtonElement;
    };
    interface HTMLWalletSelectorElement extends Components.WalletSelector, HTMLStencilElement {
    }
    var HTMLWalletSelectorElement: {
        prototype: HTMLWalletSelectorElement;
        new (): HTMLWalletSelectorElement;
    };
    interface HTMLWalletSelectorModalElement extends Components.WalletSelectorModal, HTMLStencilElement {
    }
    var HTMLWalletSelectorModalElement: {
        prototype: HTMLWalletSelectorModalElement;
        new (): HTMLWalletSelectorModalElement;
    };
    interface HTMLElementTagNameMap {
        "close-button": HTMLCloseButtonElement;
        "wallet-selector": HTMLWalletSelectorElement;
        "wallet-selector-modal": HTMLWalletSelectorModalElement;
    }
}
declare namespace LocalJSX {
    interface CloseButton {
        "onNearModalCloseEvent"?: (event: CustomEvent<MouseEvent>) => void;
    }
    interface WalletSelector {
    }
    interface WalletSelectorModal {
        /**
          * The prefered theme for the modal.
         */
        "theme"?: Theme;
    }
    interface IntrinsicElements {
        "close-button": CloseButton;
        "wallet-selector": WalletSelector;
        "wallet-selector-modal": WalletSelectorModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "close-button": LocalJSX.CloseButton & JSXBase.HTMLAttributes<HTMLCloseButtonElement>;
            "wallet-selector": LocalJSX.WalletSelector & JSXBase.HTMLAttributes<HTMLWalletSelectorElement>;
            "wallet-selector-modal": LocalJSX.WalletSelectorModal & JSXBase.HTMLAttributes<HTMLWalletSelectorModalElement>;
        }
    }
}
