module.exports = {
  arrowParens: "always",
  bracketSpacing: true,
  jsxSingleQuote: false,
  printWidth: 80,
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  useTabs: false,
  trailingComma: "es5",
  quoteProps: "as-needed",
  proseWrap: "preserve",
  insertPragma: false,
  requirePragma: false,
  bracketSameLine: false,
  endOfLine: "auto",
};