#!/usr/bin/env bash

OTP=123456
TAG=latest

npm publish dist/packages/core --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/modal-ui --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/modal-ui-js --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/wallet-utils --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/my-near-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/sender --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/math-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/nightly --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/ledger --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/wallet-connect --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/meteor-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/here-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/coin98-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/nearfi --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/welldone-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/neth --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/account-export --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/narwallets --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/xdefi --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/near-snap --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/ramper-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/near-mobile-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/mintbase-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/bitte-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/bitget-wallet --tag "${TAG}" --otp "${OTP}"
npm publish dist/packages/okx-wallet --tag "${TAG}" --otp "${OTP}"
